name: Test ringtest using NEURON wheels
on:
  push:
    branches: 
      - master
  pull_request:
    branches:
      - master
jobs:
  ci:
    name: ${{matrix.os}} / ${{matrix.version}}
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-22.04]
        version: [neuron, neuron-nightly]
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - name: Install NEURON
        run: |
          python -m pip install --upgrade pip
          python -m pip install "${{matrix.version}}"
      - name: Build .mod files
        run:  |
          nrnivmodl -coreneuron mod/
      - name: Run ringtest
        run:  |
          # Get NEURON major version
          NRNVER=$(python -c 'import neuron; print(neuron.__version__.split(".")[0])')
          echo "NEURON major version: ${NRNVER}"

          # Test NEURON
          python ringtest.py -tstop 100
          diff spk1.std reference_data/spk1.100ms.std.ref

          # Test CoreNEURON
          python ringtest.py -coreneuron -tstop 100
          sortspike spk1.std spk1.coreneuron.std
          if [ "$NRNVER" -ge 9 ]; then
            # 8.2 coreneuron mod files comment out TABLE statements
            diff spk1.coreneuron.std reference_data/spk1.100ms.std.ref
          fi
